import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Noto_Sans_KR } from "next/font/google";

/*
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
*/
const notoSans = Noto_Sans_KR({
  weight: ["300", "400", "500", "700", "900"], // 필요 가중치만 골라 쓰세요
  display: "swap",
  variable: "--font-sans",
});
/*
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
*/

export const metadata: Metadata = {
  title: "WELCOME WASH",
  description: "Generated by create next app",
};

/*
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
*/

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <body className={`${notoSans.variable} font-sans`}>
        {children}
      </body>
    </html>
  );
}
